### PR TITLE
Add pyls-isort as third party plugin in Readme

### PR DESCRIPTION
**Pull request by paradoxxxzero**
I implemented a little plugin for sorting my imports during code formatting. Could you take a look if I done this correctly? In that case you can merge this pull request to add it in the third party plugins section if you want.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @paradoxxxzero! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by gatesn** [comment]
@paradoxxxzero thanks for this! Would you mind signing the CLA so we can merge? If you don't want to sign it, I'm happy to make the PR on your behalf.

Worth noting that the formatter hooks take only the first non-None result. So you'll be competing against the built-in formatters.

**Comment by paradoxxxzero** [comment]
Yes i noticed that after, so that's why I rewrote it as a hookwrapper,
sadly it seems very hackish but it works for now (could be convenient to be
able to chain formatters).

As for the PR yes please make the changes, signing a CLA for 2 words in a
readme is a bit overkill!

**Comment by gatesn** [comment]
Closed for #180

**Pull request closed without merging**
