### PR TITLE
Support change loglevel from command line.

### PR DESCRIPTION
**Pull request by autozimu**
Also, set default loglevel to "ERROR". As right now, logger output
messages to stderr.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @autozimu! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by autozimu** [comment]
A little background https://github.com/autozimu/LanguageClient-neovim/issues/21.

Basically the issue is because pyls write huge amount of logging messages to stderr, exhausting the stderr buffer. When using Popen to open pyls as subprocess, the piped stderr is buffered, and that buffer size usually has a limit of 4K.

**Comment by gatesn** [comment]
Thanks for this @autozimu and PRs are always more than welcome! However I don't believe in this case changing the level is sufficient, it just postpones the issue instead of fixing it, c.f. #15

**Comment by gatesn** [comment]
Closed in favour of #19

**Pull request closed without merging**
