### PR TITLE
Fix: Run pytest in parallel using xdist

### PR DESCRIPTION
**Pull request by benmezger**
This runs pytest in parallel by using xdist instead. Pytest takes around ~64.88s  in my machine, it now takes around ~41.23s, which is a plus when running tests within CircleCI

### CODE REVIEW

**Comment by benmezger** [comment]
Hm, this is failing on `mypy`. I am unable to reproduce this on my machine, any ideas why this fails?

**Comment by ccordoba12** [comment]
I don't think Jedi tests could be run in parallel, so this should be avoided.

**Comment by benmezger** [comment]
@ccordoba12 this is a bit odd, as I am able to pass all tests on my machine (OSX). Why is `parso/cache.py:119` raising an `EOFError`?

**Comment by ccordoba12** [comment]
Probably several processes can't access that file at the same time on Windows.

**Comment by goanpeca** [comment]
xdist may have issues on win, so maybe just use it for non windows tests?

**Comment by benmezger** [comment]
> xdist may have issues on win, so maybe just use it for non windows tests?

I haven't found any reference of getting xdist to not run parallel tests on Windows. Anything specific I should be looking for?

**Pull request closed without merging**
