### PR TITLE
Add support for autopep8 aggressive option from config file

### PR DESCRIPTION
**Pull request by andrewzigerelli**
This is so the user can specify aggressive option in pycodestyle config file.
e.g. in ~/.config/pycodestyle
```
[pycodestyle]
aggressive = 2
```
This seems to work. E.g.
No aggressive option leave this code as is:
```python
if x == None:
```
With above pycodestyle and pull request, it makes this change:
```python
if x is None:
```

Anyone who reads this: higher aggressive options than 0 should be used with care, as x is None does not always mean the same as x == None.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @andrewzigerelli! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by goanpeca** [comment]
Thanks for working on this @andrewzigerelli 

Could you add a small test for this ?

Using the x == None example should be enough in the test

**Comment by ccordoba12** [comment]
@andrewzigerelli, please also sign the CLA agreement so we can merge your PR (we can't do it without it).

**Comment by andrewzigerelli** [comment]
Does the current ci test pycodestlye config files? I'm not familiar with ci tests

**Comment by goanpeca** [comment]
>Does the current ci test pycodestlye config files?
Yes

>I'm not familiar with ci tests

Take a look at this file https://github.com/palantir/python-language-server/blob/develop/test/plugins/test_pycodestyle_lint.py

**Comment by andrewzigerelli** [comment]
@goanpeca 
I wrote a small test and do 
```
pytest test/plugins/test_pycodestyle_lint.py -s >2 log.out
```
This reads from my ~/.config/pycodestyle and is fine, but I don't see how this will pass ci validation.
Do I have to install circleci locally to see [setup.cfg](https://github.com/palantir/python-language-server/blob/develop/setup.cfg) be preferred?

Further, [test_pycodestyle_lint.py](https://github.com/palantir/python-language-server/blob/develop/test/plugins/test_pycodestyle_lint.py) doesn't even seem to test the options defined in setup.cfg, unless I'm in the wrong file. I don't see any code which tests max-line-length = 120, or the ignore options..

**Comment by goanpeca** [comment]
Actually I think is fine to leave without a test for now :-)

**Review by goanpeca — APPROVED** [review]

**Pull request merged**
