### PR TITLE
Fix #515 don't ignore LSP client's snippet support capabilities

### LINKED ISSUE #515: pyls passes snippets to clients that don't support it
Since #499, pyls passes snippets to the client even if it declares that it doesn't support it (with `capabilities.completion.completionItem.snippetSupport`), and the only way to work around this is to pass it [specific options](https://github.com/autozimu/LanguageClient-neovim/issues/737#issuecomment-465089402).

pyls should honor standard capabilities declared by the client.

### PR DESCRIPTION
**Pull request by Shougo**
Fix #515

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @Shougo! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by Shougo** [comment]
Please test it.

**Comment by hujianxin** [comment]
Tested it, works fine

**Comment by fominok** [comment]
Really looking forward to this merge

**Comment by Shougo** [comment]
I have fixed unit tests.

**Comment by lambdacn** [comment]
ping @palantirtech

**Comment by lambdacn** [comment]
I think this pr should be merged.

**Comment by fominok** [comment]
ping @gatesn

**Comment by gatesn** [comment]
Apologies, I've been out on vacation. For expediency, I've made a few changes to this PR here: https://github.com/palantir/python-language-server/pull/529. Namely, the jedi setting for enabling snippets doesn't override what client capabilities say; and snippets are only generated for positional arguments.

**Comment by Shougo** [comment]
OK.

**Pull request closed without merging**
