### PR TITLE
Fix pycodestyle iterable options

### LINKED ISSUE #210: pycodestyle config not being read, seeing runtime errors since 0.12.0
Since upgrading to 0.12.1 (from 0.11.1) I noticed that I was getting D100 and D103 docstring warnings in my code, even though I ignored them via `$HOME/.config/pycodestyle`.  I tried adding a `setup.cfg` to the project directory but I still got the warnings.

When running `pyls` (as `pyls --tcp --port 9001 -v`) in TCP mode I saw the following output after loading a Python file. Could the issue I'm seeing be related to the pydocstyle error? 

```
[...]
2017-12-25 11:09:59,221 UTC - INFO - pyls.config.config - Loaded pyls plugin pycodestyle from <module 'pyls.plugins.pycodestyle_lint' from '/home/terr/.local/lib/python3.5/site-packages/pyls/plugins/pycodestyle_lint.py'>
[...]
2017-12-25 11:04:15,188 UTC - INFO - pyls.config.config - Loaded pyls plugin mccabe from <module 'pyls.plugins.mccabe_lint' from '/home/terr/.local/lib/python3.5/site-packages/pyls/plugins/mccabe_lint.py'>
2017-12-25 11:04:15,188 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_signature_help from <module 'pyls.plugins.signature' from '/home/terr/.local/lib/python3.5/site-packages/pyls/plugins/signature.py'>
Usage: pydocstyle [options] [<file|dir>...]
pyls: error: no such option: --tcp
```

I'm assuming the "no such option: --tcp" error doesn't occur in IO mode. I've got the most recent version of `pydocstyle` installed, 2.1.1. 

I also tried 0.12.0, where I got the same output and results (warnings about D100/D103). Version 0.11.1 still works fine, both in IO and TCP mode.

### PR DESCRIPTION
**Pull request by gatesn**
Fixes #210

### CODE REVIEW

**Comment by gatesn** [comment]
@lgeiger hopefully last iteration on this stuff!

**Comment by lgeiger** [comment]
Thanks for taking a look and maintaining this language server!

Unfortunately it looks like this doesn't fully fix the problem. I rebased #211 onto this branch and  the bug is still partially present. I hope I'm missing something obvious here 😄

**Comment by gatesn** [comment]
Will merge this as it seems to resolve #210, then will look again at your rebased branch. Thanks for testing.

**Comment by lgeiger** [comment]
Great Thanks! Rebased #211 again to make it easier.

**Pull request merged**
