### PR TITLE
Set is_saved to True in m_text_document__did_open

### LINKED ISSUE #603: pylint_lint.py returns existing diagnostics unless is_saved=True
When I open a file I expect that the file gets linted with pylint, but `python_ls.py::m_text_document__did_open()` calls `self.lint` with `is_saved=False`. pylint_lint.py will return in that case the last diagnostics, which is empty after opening the file.

### PR DESCRIPTION
**Pull request by casch-at**
Fixes #603.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @cslux! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by casch-at** [comment]
Hmm, there is still something bogus I think.
When I open a file the `m_text_document__did_open` routine gets called, which sets `is_saved` to `True`, this method calls `self.lint` which is wrapped with `_utils.py::debounce()`, but somehow the value of `is_saved` gets changed to `False` :-/... inside the debounce function???

``` log
2019-06-18 20:05:49,205 UTC - ERROR - pyls.python_ls - did_open...is_saved=True
2019-06-18 20:05:49,205 UTC - ERROR - pyls._utils - call_args={'self': <pyls.python_ls.PythonLanguageServer object at 0x7f737f5e5f60>, 'doc_uri': 'file:///SOMEFILE.py', 'is_saved': True}
2019-06-18 20:05:49,210 UTC - ERROR - pyls._utils - call_args={'self': <pyls.python_ls.PythonLanguageServer object at 0x7f737f5e5f60>, 'doc_uri': 'file:///SOMEFILE.py', 'is_saved': False}
2019-06-18 20:05:49,711 UTC - ERROR - pyls.python_ls - lint...is_saved=False
2019-06-18 20:05:49,711 UTC - ERROR - pyls.plugins.pylint_lint - is_saved =False
```

Can someone enlighten me please, and tell me what's going on here.

Thanks!

EDIT:
After I call `revert-buffer` in Emacs the pylint_lint is correctly called with `is_saved` set to `True`

``` log
2019-06-18 20:17:01,376 UTC - ERROR - pyls.python_ls - did_open...is_saved=True
2019-06-18 20:17:01,377 UTC - ERROR - pyls._utils - call_args={'self': <pyls.python_ls.PythonLanguageServer object at 0x7f737f5e5f60>, 'doc_uri': 'file:///home/cschwarzgruber/Developing/python/magenta-wan-renewal/magenta_wan_renewal.py', 'is_saved': True}
2019-06-18 20:17:01,877 UTC - ERROR - pyls.python_ls - lint...is_saved=True
2019-06-18 20:17:01,878 UTC - ERROR - pyls.plugins.pylint_lint - is_saved =True
```

**Comment by ccordoba12** [comment]
@cslux, so is this ready to be merged?

**Comment by mpanarin** [comment]
Do not merge this. I tried this fix locally not so long ago with Emacs as well and experienced a bunch of issues, like error of "Wrong line number" or something like that. Had no time to debug them though.

**Comment by casch-at** [comment]
I haven't seen this error. Can you try it again please?

**Comment by casch-at** [comment]
@ccordoba12 Regarding the issue mentioned at https://github.com/palantir/python-language-server/pull/604#issuecomment-503251436. It seems to be indeed a `lsp-mode`.

When lsp-mode starts the python-language-server, the following things happen.
 - Sending request 'initialize
 - Received response 'initialize
 - Sending notification 'initialized'
 - Sending notification 'textDocument/didOpen'
 - Sending notification 'workspace/didChangeConfiguration
 - ...

Both didOpen and didChangeConfiguration requests will result in a `self.lint` in `python_ls.py`. With my change didOpen would call the pylint_lint with `is_saved` set to `True` where as didChangeConfiguration would call the pylint with `is_saved` set to `False`. But due to debouncing, didChangeConfiguration will win, and therefore pylint_lint will not run, but instead returns an empty diagnostics object.

When I open another file in the same project everything works as expected. No errors...

I think didChangeConfiguration should be called before didOpen.

@yyoncho
@vibhavp

**Comment by mpanarin** [comment]
> @ccordoba12 Regarding the issue mentioned at [#604 (comment)](https://github.com/palantir/python-language-server/pull/604#issuecomment-503251436). It seems to be indeed a `lsp-mode`.
> 
> When lsp-mode starts the python-language-server, the following things happen.
> 
> * Sending request 'initialize
> * Received response 'initialize
> * Sending notification 'initialized'
> * Sending notification 'textDocument/didOpen'
> * Sending notification 'workspace/didChangeConfiguration
> * ...
> 
> Both didOpen and didChangeConfiguration requests will result in a `self.lint` in `python_ls.py`. With my change didOpen would call the pylint_lint with `is_saved` set to `True` where as didChangeConfiguration would call the pylint with `is_saved` set to `False`. But due to debouncing, didChangeConfiguration will win, and therefore pylint_lint will not run, but instead returns an empty diagnostics object.
> 
> When I open another file in the same project everything works as expected. No errors...
> 
> I think didChangeConfiguration should be called before didOpen.
> 
> @yyoncho
> @vibhavp

Okay, now i remember. The issue with line number i mentioned is when i added `save=True` to `didChangeConfiguration` so sorry for misleading info.

**Comment by casch-at** [comment]
@mpanarin NP, thanks for checking again!

**Comment by gatesn** [comment]
Shouldn't we just include the `save` kwarg in the key for debouncing?

**Comment by yyoncho** [comment]
> I think didChangeConfiguration should be called before didOpen.

I fixed that on lsp-mode side.

**Comment by casch-at** [comment]
@yyoncho Thank you! Works now! 

@ccordoba12 This can be merged now.

**Comment by ccordoba12** [comment]
@gatesn, what do you say about this one?

**Review by gatesn — APPROVED** [review]

**Comment by gatesn** [comment]
The only odd thing is that `is_saved` might be presumed to mean that the current content of the file exists up-to-date on disk / can be accessed from the doc uri. But maybe it's not a problem

**Pull request merged**
