### PR TITLE
Support pyenv virtualenv

### PR DESCRIPTION
**Pull request by 15cm**
Add pyenv support so that things like ".python-version" works. The first path in Document._extra_sys_path will be used to find the virtualenv via `pyenv prefix $path`.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @15cm! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by gatesn** [comment]
I don't think I understand your use-case. What client are you using? Why would you like to add site-packages of a different Python environment to the language server vs running the language server _in_ that environment?

**Comment by 15cm** [comment]
I am using lsp-mode on Emacs. If I follow the latter way, I need to have
pyls installed in every environment. That's acceptable to me but I also
need to know which pyls to launch in lsp-mode. That's the issue for me. My
goal is that we have one pyls server and documents will adjust the env
according to the pyenv they are in.

**Comment by 15cm** [comment]
Made a mistake in the goal part. Let me repharse my goal: have one pyls
entry and have corresponding environment in each pyls process that's
launched by different projects.

**Comment by ccordoba12** [comment]
> have one pyls entry and have corresponding environment in each pyls process that's launched by different projects.

Then this is not the right approach. You need to add support for [Jedi environments](https://jedi.readthedocs.io/en/latest/_modules/jedi/api/environment.html) here instead.

**Comment by 15cm** [comment]
For _pyls_, [Jedi Environments](https://jedi.readthedocs.io/en/latest/_modules/jedi/api/environment.html) only provides some utility function and class, I think anyway we should modify the `sys_path` that's passed to Jedi to support _pyenv_ since only _pyls_ have the project root for a `document`.
How do you think if I add pyenv support in _Jedi_ and we do something like this in _pyls_?
```python
def sys_path(self):
    # Some check...
    project_root = self._extra_sys_path[0]
    path = list(self._extra_sys_path)
    environment = jedi.api.environment.get_cached_environment_for_project(project_root)
    path.extend(environment.get_sys_path())
    return path
```

**Comment by bersace** [comment]
I confirm that I expect pyls to respect `.python-version` while analyzing a project.

@ccordoba12 how do you manage venv/python version in different project and pyls ? Say having python2 and python3 projects ?

**Comment by bersace** [comment]
See here http://www.lexev.org/en/2019/sublime-text-and-language-server-protocol-lsp/ . One sets `VIRTUAL_ENV` envvar in Sublime . Maybe is sublime running a pyls process per project ?

**Comment by ccordoba12** [comment]
@bersace, see PR #680.

**Comment by 15cm** [comment]
As PR #680 is on the same path as I originally proposed , any plan to support `pyenv` in one `pyls` process? As the `pyenv` part have been already done in this PR, I don't mind porting it to the new code.

**Comment by bersace** [comment]
@ccordoba12 Thanks ! If i understand correctly : lsp-mode must configure pyls with extra path from pyenv ?

**Comment by ccordoba12** [comment]
Not the extra path of the intepreter's `sys.path`, but the path to interpreter directly in the `jedi.environment` variable:

https://github.com/palantir/python-language-server/pull/680/files#diff-942a8b6d9b93cba7f0d40bd9db4a4d2fR37

**Comment by syphar** [comment]
@ccordoba12 when debugging my problem I stumbled on this PR, 

for me pyls doesn't work when using a pyenv-virtualenv, but is fine when using a virtualenv on the same python version/executable than the global pyls. 

How to set/use `jedi.api.environemnt`? 

(I'm using `LanguageClient-neovim`)

**Comment by ccordoba12** [comment]
You need to set the Python interpreter of your env in the `jedi.environment` option, then send a `workspace/didChangeConfiguration` to the server.

However, I don't know how that's done in `LanguageClient-neovim`, sorry.

**Comment by syphar** [comment]
Thank you very much @ccordoba12 ! I'll figure it out.

**Comment by 15cm** [comment]
Thanks for your work @ccordoba12! It's a nice implementation that delegates the environment passing to LSP clients.

**Comment by ccordoba12** [comment]
Actually that was done by @goanpeca. And we're already using it successfully in Spyder.

**Comment by carter54** [comment]
@15cm @ccordoba12 @syphar 
Hi, thanks for this work. I am wondering that can we pass the current using python interpreter to Jedi environment throught workspace/didChangeConfiguration or we need to set jedi environment manually and use workspace/didChangeConfiguration to tell lsp server the config has been changed? Thx!

**Comment by carter54** [comment]
> @15cm @ccordoba12 @syphar
> Hi, thanks for this work. I am wondering that can we pass the current using python interpreter to Jedi environment throught workspace/didChangeConfiguration or we need to set jedi environment manually and use workspace/didChangeConfiguration to tell lsp server the config has been changed? Thx!

I have figured out this, workspace/didChangeConfiguration can send Jedi environment to the server, and server will change the python interpreter in jedi.environment! Great job! Thx!

**Pull request closed without merging**
