### PR TITLE
README: Add pointer to list of configuration options

### LINKED ISSUE #765: What LSP configuration options are supported?
Is there a reference page anywhere about what settings python-language-server will recognize in LSP configuration? The README mentions two options, `pyls.configurationSources` and `pyls.plugins.pydocstyle.enabled`, and I've found no other info about it.

### PR DESCRIPTION
**Pull request by dbarnett**
Fixes #765.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @dbarnett! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by dbarnett** [comment]
I'm a Google employee and Google already has a signed CLA on file with Palantir.

**Comment by ccordoba12** [comment]
I'm sorry but I can't merge this PR unless you sign the CLA here.

**Comment by dbarnett** [comment]
K, I'm not sure that's how CLAs are supposed to work, but it sounds like my 2-line README fix just isn't going to get submitted then, and I don't understand why you have a "CORPORATE CONTRIBUTOR" section at https://cla.palantir.com/ if Google has submitted that CLA and you're saying I still for some reason don't have permission to contribute on behalf of my company.

**Comment by dbarnett** [comment]
Anyway, it would be great if someone could update the README since I'm trying to take initiative and getting sent in circles.

**Comment by ccordoba12** [comment]
Sorry, I'm not a Palantir employee nor I'm affiliated with it in any way. I'm just helping to maintain this project and I'm unable to merge your PR without you signing their CLA.

Since you seem unwilling to do that, I'm going to close this one, sorry.

**Comment by dbarnett** [comment]
Okay, I was able to sign the individual CLA. Are you able to reopen this PR?

**Pull request merged**
