### PR TITLE
Support configuration from multiple sources

### LINKED ISSUE #169: pycodestyle doesn't report issues if entry in setup.cfg exists
It looks like the pycodestyle plugin doesn't report any issue as soon as a configuration is made in the setup.cfg

The setup.cfg contains the following lines.

```
[flake8]
ignore = D100,D101,D104,E722
exclude = .git,__init__.py
max-line-length = 80

[mypy]
python_version = 3.3
silent_imports = True
ignore_errors = True
strict_optional = False

[pycodestyle]
ignore = E722
exclude = .git,__init__.py
max-line-length = 80

[pydocstyle]
ignore = D100,D101,D104
max-line-length = 80
```

### Expected behavior

All lines longer than 80 chars should be warned to be too long, but E722 (bare excepts) should be ignored.

### Actual behavior

With a `[pycodestyle]` section in the setup.cfg pycodestyle doesn't return any warnings/errors. Lines longer than 80 chars are accepted.

The debug log shows :

```
2017-10-24 19:20:11,635 UTC - DEBUG - pyls.plugins.pycodestyle_lint - Got pycodestyle config: {'verbose': 0, 'quiet': 0, 'repeat': True, 'exclude': '.git,__init__.py', 'filename': '*.py', 'select': '', 'ignore': 'E722', 'show_source': None, 'show_pep8': None, 'statistics': None, 'count': None, 'max_line_length': 80, 'hang_closing': None, 'format': 'default', 'diff': None, 'benchmark': None}
```

If the `[pycodestyle]` section is commented out both issues are recognized.

### LINKED ISSUE #173: Support linting configuration from other tooling formats
Although the language server supports a lot of common linting tools, there are many different ways of configuring them. We also have a few bugs right now (#169) around how we parse configs. Looks like there should be a more robust / centralised way of parsing configs.

e.g. Prospector #161 and Flake8 #172

### LINKED ISSUE #185: [feature] give possibility to disable pyflakes checks
Hi
Is this supported ? I would like to disable certain checks for Pyflakes, e.g. E501.

### PR DESCRIPTION
**Pull request by gatesn**
This PR introduces the idea of a configuration source. Implemented are pycodestyle and flake8 sources. PyLS configuration can be set to choose one or more configuration sources from which to merge configs.

Fixes #165 
Fixes #169 
Fixes #173
Fixes #185

### CODE REVIEW

**Comment by deathaxe** [comment]
Great approach! 👍 

Unfortunately this PR causes no more diagnostics to be sent back at all, no matter of existence of `setup.cfg` within `~/.config` or a project folder. 

I just pulled the latest master and copied the pyls over my python site-packages.

Anything else needed?

**Comment by gatesn** [comment]
Hmmm, are you able to get me some debug logs?

**Comment by deathaxe** [comment]
The server is started with `pyls --log-file C:\\data\\pyls.log -vv` from Sublime Text using the LSP package.

1. Opened a small python file which does not initially contains issues.
2. Added a long comment line longer than 120 chars which would normally cause pycodestyle to complain.

I saw some `log.debug()` calls in the pycodestyle plugin, which don't appear in the log file. Looks like the plugins are not executed at all for some reason?

Maybe off-topic (sorry), but I think the filter in https://github.com/palantir/python-language-server/blob/3c1f18361179f3a687bdef6209e136a10bbf043f/pyls/plugins/pycodestyle_lint.py#L23 does not prevent emty-string-value-settings like `"exclude": ""`.

The previous commit works fine.

Content of pyls.log

```
2017-11-06 21:21:40,428 UTC - INFO - pyls.language_server - Starting PythonLanguageServer IO language server
2017-11-06 21:21:40,428 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {"capabilities": {"workspace": {"applyEdit": true}, "textDocument": {"completion": {"completionItem": {"snippetSupport": true}}, "synchronization": {"didSave": true}}}, "rootPath": "C:\\\\Apps\\\\Sublime\\\\Data\\\\Packages\\\\CNC Sinumerik 840D", "rootUri": "file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D", "processId": 4564}}'
2017-11-06 21:21:40,428 UTC - DEBUG - pyls.language_server - Language server intialized with {'capabilities': {'workspace': {'applyEdit': True}, 'textDocument': {'completion': {'completionItem': {'snippetSupport': True}}, 'synchronization': {'didSave': True}}}, 'rootPath': 'C:\\Apps\\Sublime\\Data\\Packages\\CNC Sinumerik 840D', 'rootUri': 'file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D', 'processId': 4564}
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_completion from <module 'pyls.plugins.jedi_completion' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\jedi_completion.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_definition from <module 'pyls.plugins.definition' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\definition.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_hover from <module 'pyls.plugins.hover' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\hover.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_references from <module 'pyls.plugins.references' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\references.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_signature_help from <module 'pyls.plugins.signature' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\signature.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin jedi_symbols from <module 'pyls.plugins.symbols' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\symbols.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin mccabe from <module 'pyls.plugins.mccabe_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\mccabe_lint.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin pycodestyle from <module 'pyls.plugins.pycodestyle_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pycodestyle_lint.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin pydocstyle from <module 'pyls.plugins.pydocstyle_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pydocstyle_lint.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin pyflakes from <module 'pyls.plugins.pyflakes_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pyflakes_lint.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin rope_completion from <module 'pyls.plugins.rope_completion' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\rope_completion.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin rope_rename from <module 'pyls.plugins.rope_rename' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\rope_rename.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin yapf from <module 'pyls.plugins.format' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\format.py'>
2017-11-06 21:21:40,787 UTC - INFO - pyls.config.config - Loaded pyls plugin pyls_mypy from <module 'pyls_mypy.plugin' from 'c:\\apps\\python36\\lib\\site-packages\\pyls_mypy\\plugin.py'>
2017-11-06 21:21:40,787 UTC - DEBUG - pyls.config.config -   pyls_settings [hook]
      config: <pyls.config.config.Config object at 0x00000257E55C7780>

2017-11-06 21:21:40,787 UTC - DEBUG - pyls.config.config -   finish pyls_settings --> [{'plugins': {'pydocstyle': {'enabled': False}}}] [hook]

2017-11-06 21:21:40,787 UTC - DEBUG - pyls.config.config -   pyls_initialize [hook]
      config: <pyls.config.config.Config object at 0x00000257E55C7780>
      workspace: <pyls.workspace.Workspace object at 0x00000257E55C74E0>
      document: None

2017-11-06 21:21:40,787 UTC - DEBUG - pyls.config.config -   finish pyls_initialize --> [] [hook]

2017-11-06 21:21:40,787 UTC - DEBUG - pyls.config.config -   pyls_commands [hook]
      config: <pyls.config.config.Config object at 0x00000257E55C7780>
      workspace: <pyls.workspace.Workspace object at 0x00000257E55C74E0>
      document: None

2017-11-06 21:21:40,787 UTC - DEBUG - pyls.config.config -   finish pyls_commands --> [] [hook]

2017-11-06 21:21:40,787 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc": "2.0", "method": "initialized", "params": {}}'
2017-11-06 21:21:40,803 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc": "2.0", "method": "textDocument/didOpen", "params": {"textDocument": {"version": 0, "text": "# -*- encoding: utf-8 -*-\\n\\n\\"\\"\\"Publish only required classes to Sublime Text.\\"\\"\\"\\n\\nimport sublime\\n\\n# export commands\\nfrom .gcode.commands.beautify import S840dBeautifyCommand\\nfrom .gcode.commands.minify import S840dMinifyCommand\\nfrom .gcode.commands.protect import S840dProtectCommand\\nfrom .gcode.commands.blockno import S840dRenumberCommand\\nfrom .gcode.commands.goto import S840dGotoDefinitionCommand\\nfrom .plc.commands.merge import S840dAwlLoadMergeCommand\\nfrom .plc.commands.split import S840dAwlSaveSplitCommand\\n\\n# export event handlers\\nfrom .hmi.events import S840dHmiEvents\\nfrom .gcode.events import S840dNckViewEvents\\n\\n\\ndef plugin_loaded():\\n    \\"\\"\\"This function is called by ST3 after all plugins are loaded.\\"\\"\\"\\n    apply_essential_settings(\\"s840d_arc\\")\\n    apply_essential_settings(\\"s840d_gcode\\")\\n    apply_essential_settings(\\"s840d_hmi\\")\\n\\n\\ndef apply_essential_settings(syntax):\\n    \\"\\"\\"Apply essential settings from template to user file.\\n\\n    This function loads the default values from a syntax settings file\\n    coming with this package as resource and copies all values to the\\n    /Packages/User/<syntax>.sublime-settings.\\n    \\"\\"\\"\\n    dirty = False\\n    file_name = \\"%s.sublime-settings\\" % syntax\\n    settings = sublime.load_settings(file_name)\\n    template = sublime.decode_value(sublime.load_resource(\\n        sublime.find_resources(file_name)[0]))\\n    for key in template.keys():\\n        value = template[key]\\n        # An essential setting was changed and needs update in the user syntax\\n        # settings file.\\n        if value != settings.get(key):\\n            dirty = True\\n            if value:\\n                # Apply essential settings.\\n                settings.set(key, value)\\n            else:\\n                # Keys to remove are marked with \'None\' value.\\n                settings.erase(key)\\n    if dirty:\\n        # Save settings if at least one setting was changed.\\n        sublime.save_settings(file_name)\\n", "languageId": "python", "uri": "file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D/plugin.py"}}}'
2017-11-06 21:21:40,803 UTC - DEBUG - pyls.config.config -   pyls_document_did_open [hook]
      config: <pyls.config.config.Config object at 0x00000257E55C7780>
      workspace: <pyls.workspace.Workspace object at 0x00000257E55C74E0>
      document: file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D/plugin.py

2017-11-06 21:21:40,803 UTC - DEBUG - pyls.config.config -   finish pyls_document_did_open --> [] [hook]

2017-11-06 21:21:41,303 UTC - DEBUG - pyls.config.config -   pyls_lint [hook]
      config: <pyls.config.config.Config object at 0x00000257E55C7780>
      workspace: <pyls.workspace.Workspace object at 0x00000257E55C74E0>
      document: file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D/plugin.py

2017-11-06 21:22:04,772 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc": "2.0", "method": "textDocument/didChange", "params": {"contentChanges": [{"text": "# -*- encoding: utf-8 -*-\\n\\n\\"\\"\\"Publish only required classes to Sublime Text.\\"\\"\\"\\n\\nimport sublime\\n\\n# export commands\\nfrom .gcode.commands.beautify import S840dBeautifyCommand\\nfrom .gcode.commands.minify import S840dMinifyCommand\\nfrom .gcode.commands.protect import S840dProtectCommand\\nfrom .gcode.commands.blockno import S840dRenumberCommand\\nfrom .gcode.commands.goto import S840dGotoDefinitionCommand\\nfrom .plc.commands.merge import S840dAwlLoadMergeCommand\\nfrom .plc.commands.split import S840dAwlSaveSplitCommand\\n\\n# export event handlers\\nfrom .hmi.events import S840dHmiEvents\\nfrom .gcode.events import S840dNckViewEvents\\n\\n\\ndef plugin_loaded():\\n    \\"\\"\\"This function is called by ST3 after all plugins are loaded.\\"\\"\\"\\n    apply_essential_settings(\\"s840d_arc\\")\\n    apply_essential_settings(\\"s840d_gcode\\")\\n    apply_essential_settings(\\"s840d_hmi\\")\\n\\n\\ndef apply_essential_settings(syntax):\\n    \\"\\"\\"Apply essential settings from template to user file.\\n\\n    This function loads the default values from a syntax settings file\\n    coming with this package as resource and copies all values to the\\n    /Packages/User/<syntax>.sublime-settings.\\n    \\"\\"\\"\\n    dirty = False\\n    file_name = \\"%s.sublime-settings\\" % syntax\\n    settings = sublime.load_settings(file_name)\\n    template = sublime.decode_value(sublime.load_resource(\\n        sublime.find_resources(file_name)[0]))\\n    for key in template.keys():\\n        value = template[key]\\n        # An essential setting was changed and needs update in the user syntax df\\u00f6asfdjas \\u00f6jsad\\u00f6fjsad\\u00f6fjsalfjsaldfjs\\u00f6ldjfs\\u00f6ladjf\\u00f6lsadjf\\u00f6slfj\\n        # settings file.\\n        if value != settings.get(key):\\n            dirty = True\\n            if value:\\n                # Apply essential settings.\\n                settings.set(key, value)\\n            else:\\n                # Keys to remove are marked with \'None\' value.\\n                settings.erase(key)\\n    if dirty:\\n        # Save settings if at least one setting was changed.\\n        sublime.save_settings(file_name)\\n"}], "textDocument": {"version": 1, "uri": "file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D/plugin.py"}}}'
2017-11-06 21:22:05,272 UTC - DEBUG - pyls.config.config -   pyls_lint [hook]
      config: <pyls.config.config.Config object at 0x00000257E55C7780>
      workspace: <pyls.workspace.Workspace object at 0x00000257E55C74E0>
      document: file:///C:/Apps/Sublime/Data/Packages/CNC%20Sinumerik%20840D/plugin.py

```


Content of LSP's debug_log from Sublime Text's console

```
LSP: starting in C:\Apps\Sublime\Data\Packages\CNC Sinumerik 840D
LSP: starting ['pyls', '--log-file', 'C:\\data\\pyls.log', '-vv']
LSP:  --> initialize
Package Control: Skip cleanup C:\Apps\Sublime\Data\Packages\User
LSP:      {'capabilities': {'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'codeActionProvider': True, 'documentFormattingProvider': True, 'documentSymbolProvider': True, 'hoverProvider': True, 'textDocumentSync': 2, 'documentRangeFormattingProvider': True, 'executeCommandProvider': {'commands': []}, 'codeLensProvider': {'resolveProvider': False}, 'referencesProvider': True, 'definitionProvider': True, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'renameProvider': True}}
LSP:  --> initialized
LSP: pyls client registered for window 2
LSP:  --> textDocument/didOpen
LSP:  --> textDocument/didChange
```

**Comment by gatesn** [comment]
Note how you see lines like `finish pyls_commands --> [] [hook]`, there are no `finish pyls_lint ...` messages anywhere. Suggesting something is hanging.

**Comment by deathaxe** [comment]
Looks like `pydocstyle_lint.py` is the culprit. After adding some debug messages `python_ls.py -> PythonLanguageServer.lint()` seems to be the only/last called function. After surrounding its code into a try ... except statement, I found the `pydocstyle_lint.py -> pyls_lint()` being the last linter, which was called (even though the plugin is disabled by default, isn't it?) . It throws the following exception which is just ignored by pyls, because of the debounce decorator. After removing the decorator the log file shows:

```
2017-11-07 18:47:26,884 UTC - DEBUG - pyls.config.config -   pyls_document_did_open [hook]
      config: <pyls.config.config.Config object at 0x0000028DD49FA240>
      workspace: <pyls.workspace.Workspace object at 0x0000028DD49D4BA8>
      document: file:///C:/Apps/python36/Lib/site-packages/pyls/python_ls.py

2017-11-07 18:47:26,884 UTC - DEBUG - pyls.config.config -   finish pyls_document_did_open --> [] [hook]

2017-11-07 18:47:26,884 UTC - DEBUG - pyls.python_ls - invoke lint
2017-11-07 18:47:26,884 UTC - DEBUG - pyls.config.config -   pyls_lint [hook]
      config: <pyls.config.config.Config object at 0x0000028DD49FA240>
      workspace: <pyls.workspace.Workspace object at 0x0000028DD49D4BA8>
      document: file:///C:/Apps/python36/Lib/site-packages/pyls/python_ls.py

2017-11-07 18:47:26,884 UTC - DEBUG - pyls.plugins.pyflakes_lint - Initializing pyflakes...
2017-11-07 18:47:26,884 UTC - DEBUG - pyls.plugins.pydocstyle_lint - Initializing PyDocstyle...
2017-11-07 18:47:26,884 UTC - ERROR - pyls.language_server - CAUGHT
Traceback (most recent call last):
  File "c:\apps\python36\lib\optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "c:\apps\python36\lib\optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "c:\apps\python36\lib\optparse.py", line 1480, in _process_long_opt
    opt = self._match_long_opt(opt)
  File "c:\apps\python36\lib\optparse.py", line 1465, in _match_long_opt
    return _match_abbrev(opt, self._long_opt)
  File "c:\apps\python36\lib\optparse.py", line 1670, in _match_abbrev
    raise BadOptionError(s)
optparse.BadOptionError: no such option: --log-file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 132, in m_text_document__did_open
    self.lint(textDocument['uri'])
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 104, in lint
    diagnostics = self._hook('pyls_lint', doc_uri)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 30, in _hook
    return self._hook_caller(hook_name)(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 680, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 240, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 201, in __call__
    return outcome.get_result()
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 54, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 37, in from_call
    result = func()
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 199, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 234, in <lambda>
    methods, kwargs, specopts=hook.spec_opts, hook=hook
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 115, in execute
    return outcome.get_result()
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 54, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 94, in execute
    res = hook_impl.function(*args)
  File "c:\apps\python36\lib\site-packages\pyls\plugins\pydocstyle_lint.py", line 23, in pyls_lint
    conf.parse()
  File "c:\apps\python36\lib\site-packages\pydocstyle\config.py", line 109, in parse
    self._options, self._arguments = self._parse_args()
  File "c:\apps\python36\lib\site-packages\pydocstyle\config.py", line 370, in _parse_args
    options, arguments = self._parser.parse_args(args, values)
  File "c:\apps\python36\lib\optparse.py", line 1389, in parse_args
    self.error(str(err))
  File "c:\apps\python36\lib\optparse.py", line 1569, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "c:\apps\python36\lib\optparse.py", line 1559, in exit
    sys.exit(status)
SystemExit: 2
```

After commenting out the pydocstyle code, diagnostics work well again.

Alternatively I removed the `--log-file` argument from the pyls command line. After that, it works again, too. Seems you try to forward the pyls command line to pydocstyle?

**Comment by gatesn** [comment]
You're right, looks like the opt parser in pydocstyle reads from `sys.argv`! 

Can you try removing this line: https://github.com/palantir/python-language-server/blob/develop/pyls/plugins/pydocstyle_lint.py#L22

**Comment by deathaxe** [comment]
Fails, too with following log:

```

2017-11-07 21:10:52,201 UTC - DEBUG - pyls.config.config -   finish pyls_document_did_open --> [] [hook]

2017-11-07 21:10:52,201 UTC - DEBUG - pyls.python_ls - invoke lint
2017-11-07 21:10:52,201 UTC - DEBUG - pyls.config.config -   pyls_lint [hook]
      config: <pyls.config.config.Config object at 0x000001B2EDF5B198>
      workspace: <pyls.workspace.Workspace object at 0x000001B2EDF34AC8>
      document: file:///C:/Apps/python36/Lib/site-packages/pyls/python_ls.py

2017-11-07 21:10:52,201 UTC - DEBUG - pyls.plugins.pyflakes_lint - Initializing pyflakes...
2017-11-07 21:10:52,201 UTC - INFO - pydocstyle.utils - pydocstyle lint ...
2017-11-07 21:10:52,201 UTC - ERROR - pyls.language_server - CAUGHT
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 123, in m_text_document__did_open
    self.lint(textDocument['uri'])
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 101, in lint
    self.workspace.publish_diagnostics(doc_uri, flatten(self._hook('pyls_lint', doc_uri)))
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 27, in _hook
    return self._hook_caller(hook_name)(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 680, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 240, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 201, in __call__
    return outcome.get_result()
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 54, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 37, in from_call
    result = func()
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 199, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 234, in <lambda>
    methods, kwargs, specopts=hook.spec_opts, hook=hook
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 115, in execute
    return outcome.get_result()
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 54, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 94, in execute
    res = hook_impl.function(*args)
  File "c:\apps\python36\lib\site-packages\pyls\plugins\pydocstyle_lint.py", line 27, in pyls_lint
    for filename, checked_codes, ignore_decorators in conf.get_files_to_check():
  File "c:\apps\python36\lib\site-packages\pydocstyle\config.py", line 21, in _decorator
    raise RuntimeError('using an uninitialized configuration')
RuntimeError: using an uninitialized configuration
2017-11-07 21:10:52,201 UTC - ERROR - jsonrpc.manager - API Exception: {'type': 'RuntimeError', 'args': ('using an uninitialized configuration',), 'message': 'using an uninitialized configuration'}
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\jsonrpc\manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 123, in m_text_document__did_open
    self.lint(textDocument['uri'])
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 101, in lint
    self.workspace.publish_diagnostics(doc_uri, flatten(self._hook('pyls_lint', doc_uri)))
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 27, in _hook
    return self._hook_caller(hook_name)(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 680, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 240, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 201, in __call__
    return outcome.get_result()
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 54, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 37, in from_call
    result = func()
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 199, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "c:\apps\python36\lib\site-packages\pluggy\__init__.py", line 234, in <lambda>
    methods, kwargs, specopts=hook.spec_opts, hook=hook
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 115, in execute
    return outcome.get_result()
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 54, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\apps\python36\lib\site-packages\pluggy\callers.py", line 94, in execute
    res = hook_impl.function(*args)
  File "c:\apps\python36\lib\site-packages\pyls\plugins\pydocstyle_lint.py", line 27, in pyls_lint
    for filename, checked_codes, ignore_decorators in conf.get_files_to_check():
  File "c:\apps\python36\lib\site-packages\pydocstyle\config.py", line 21, in _decorator
    raise RuntimeError('using an uninitialized configuration')
RuntimeError: using an uninitialized configuration
```

I guess you'll need to change the config like it's done in pycodestyle. Not even sure, why pydocstyle is designed to lint several files as only one document path is passed.

**Pull request merged**
