### PR TITLE
Initialized hook

### PR DESCRIPTION
**Pull request by jroitgrund**

### CODE REVIEW

**Comment by ccordoba12** [comment]
What's the purpose of this?

**Comment by jroitgrund** [comment]
This lets plugins react to the client's initialize message.

**Review by gatesn — APPROVED** [review]

**Comment by gatesn** [comment]
Generally ok adding hooks that line up with LSP messages

**Comment by ccordoba12** [comment]
Why are there two tags (`0.31.7` and `0.32.0`) for the same commit after this PR was merged?

**Comment by gatesn** [comment]
I think lack of communication.. we both released after the PR merged and apparently have different definitions of semver!

**Comment by ccordoba12** [comment]
Ok, but given that version `0.32.0` was not uploaded to PyPI:

https://pypi.org/project/python-language-server/#history

I'd suggest to remove that tag and its corresponding release.

**Comment by gatesn** [comment]
👍

**Pull request merged**
