### PR TITLE
The error report must explicitly call _ignore_code() before accept

### PR DESCRIPTION
**Pull request by evandrocoan**
an error code and the `option` must to be None, so it cannot have
that default value. Fixes palantir/python-language-server#233 pycodesytle plugin is wrongly instantiated

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @evandrocoan! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by gatesn** [comment]
@evandrocoan would love to merge this change, could you sign the CLA please?

**Comment by evandrocoan** [comment]
I do not understand this:
`
By selecting Adopt and Sign, I agree that the signature and initials will be the electronic representation of my signature and initials for all purposes when I (or my agent) use them on documents, including legally binding contracts - just the same as a pen-and-paper signature or initial.
`
image

I do not have an account on that site (10 dollars monthly), and I have a few questions:

1. Where this signature mine will be saved?
1. What prevents someone else using it in my name?

**Comment by evandrocoan** [comment]
I make my own account on docusign, and setup my signature. But your link does not allow to login with my account.

**Pull request merged**
