### PR TITLE
Add support for multiple workspaces

### PR DESCRIPTION
**Pull request by andfoy**
This PR enables multi-root support for pyls, thus, enabling a single server to manage multiple workspaces for a single client.

cc @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
I think the errors in Circle were caused by Jedi 0.14. That should be fixed by PR #607, so please merge with master to get the fix.

**Comment by andfoy** [comment]
@ccordoba12 I'll add a test, and this one should be ready to merge

**Comment by andfoy** [comment]
@ccordoba12 This one is ready and tested

**Comment by ccordoba12** [comment]
@andfoy, please solve the merge conflict so I can merge this one. Thanks!

**Review by ccordoba12 — APPROVED** [review]
Thanks @andfoy!

**Pull request merged**
