### PR TITLE
use difflib to generate TextEdits

### PR DESCRIPTION
**Pull request by purpleP**
I've used [hypothesis](https://hypothesis.readthedocs.io/en/latest) for testing

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/python-language-server](https://github.com/palantir/python-language-server), @purpleP! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by purpleP** [comment]
@gatesn Is this isn't merged because status checks haven't completed? If so what can I do to complete them?

**Comment by purpleP** [comment]
@gatesn Is this isn't merged because status checks haven't completed? If so what can I do to complete them?

**Comment by gatesn** [comment]
I'm unsure of this PR since it introduces a fair amount of complexity. Given the language server rarely returns the full document I wonder if it's worth taking on the complexity?

I'd also prefer not to introduce a new testing framework. Pytest parameterised tests ought to be sufficient?

**Comment by purpleP** [comment]
@gatesn Do what you want with it. I'm not interested in using yapf anymore. But if you want my opinion - it's not that complex and what's more important it's the right thing to do, because it's just a correct implementation of a protocol. And no, parameterized test isn't a replacement for property based tests.

**Comment by ccordoba12** [comment]
Closing because we can't deal with this in our side right now.

**Pull request closed without merging**
