### PR TITLE
Switch to Popen.communicate() to avoid IO deadlocks in flake8 plugin

### PR DESCRIPTION
**Pull request by rdugan**
Fix to address https://github.com/palantir/python-language-server/issues/751

### CODE REVIEW

**Comment by ccordoba12** [comment]
@youben11, please review this one.

**Review by goanpeca — APPROVED** [review]
Thanks for the fix @rdugan !

I guess writing a regression test for this might be tricky. Any ideas?

**Comment by rdugan** [comment]
No problem...  It's a pretty minor change, which I thought it would just be a quick drop in replacement for the existing functionality (and covered by existing tests).  The test failures were unexpected, unfortunately I didn't have time to investigate yet.

**Comment by goanpeca** [comment]
@rdugan You need to update the test that is failing. The test was doing some mocking and the mocking now fails because the mocked communicate call is not returning something that makes sense.

Something quick and dirty like:

```python
def test_flake8_config_param(config):

    class PopenMock:
        def __init__(self, *args, **kwargs):
            PopenMock.args = args

        def communicate(self):
            return bytes(), bytes()

    with patch('pyls.plugins.flake8_lint.Popen', new=PopenMock) as popen_mock:
        flake8_conf = '/tmp/some.cfg'
        config.update({'plugins': {'flake8': {'config': flake8_conf}}})
        _name, doc = temp_document(DOC)

        flake8_lint.pyls_lint(config, doc)
        call_args = popen_mock.args[0]

        assert 'flake8' in call_args
        assert '--config={}'.format(flake8_conf) in call_args

```

Might work!

---

On another note, you made this PR from your develop branch to the develop branch, and you should have created a separate branch first. 

```bash
git checkout develop
git checkout -b branch-with-this-fix  # silly example name
# Changes, git add git commit
git push branch-with-this-fix  # silly example name
```

So it is better if you create a new PR like this.

**Review by goanpeca — CHANGES_REQUESTED** [review]
See the last comment!

**Comment by rdugan** [comment]
Replaced w/ PR #757

**Pull request closed without merging**
